baseurl = "https://blog.linuxmint.pl/"
languageCode = "PL-pl"
Title = "Blog o niczym"
# Copyright notice. This is displayer in the footer.
#copyright = "(c) Hsin-Hao Yu"
theme = "pickles_hhyu"
paginate = 5

[params]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "linuxmintpl"
  twitter = "linuxmintpl"
#  author = "Hsin-Hao Yu"
  authorwebsite = "https://linuxmint.pl"
#  avatar = "/sitewide/logo.png"
#  contact = "mailto:mati75@linuxmint.pl"
#  bio = "A Taiwanese scientist living in Melbourne"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Jeszcze nie wiemy co tu zrobimy"
  # Logo image. This is displayed ogp image.
  logo = "logo.png"
  favicon = "/path/to/favicon"

  ## specific to this forked version
  micropaginate = 10
  userelated = false

[[menu.main]]
    identifier = "Update"
    name       = "/Updates"
    weight     = 3

[[menu.main]]
    parent     = "Update"
    name       = "Blog"
    url        = "/"
    weight     = 1

[[menu.main]]
    parent     = "Update"
    name       = "Notes"
    url        = "/micro/"
    weight     = 2

[[menu.main]]
    parent     = "Update"
    name       = "Resources"
    url        = "https://github.com/hsinhaoyu/resources"
    weight     = 3


[[menu.main]]
    name       = "Tags"
    url        = "/tags"
    weight     = 4

[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 40

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = false

    # Will lower case keywords in both queries and in the indexes.
    toLower = false

    [[related.indices]]
    name = "keywords"
    weight = 150
    [[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
    [[related.indices]]
    name  = "tags"
    weight = 100
    [[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2017"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
